# -------- This file has been automatically generated by configure ---------
TARGET = lpg++
CFLAGS = -O3  -DNDEBUG  -Wall -static
CFLAGS = -g  -DNDEBUG -fpermissive -DYYERROR_VERBOSE -Wall -static
LIBS=  -lm 
CC= g++
