# -------- This file has been automatically generated by configure ---------
TARGET = lpg++
CFLAGS = -O3  -DNDEBUG  -Wall
CFLAGS = -g  -DNDEBUG -fpermissive -DYYERROR_VERBOSE -Wall
LIBS=  -lm
CC= g++
