#!/bin/bash

if [ "$#" = 0 ]; then
    echo "#!/bin/bash 

    java -classpath "$(pwd)"/out/:"$(pwd)"/libs/* main \"\$@\"" > enhsp
    chmod +x enhsp
else
    echo "#!/bin/bash 

    java "$1 $2" -classpath "$(pwd)"/out/:"$(pwd)"/libs/* main \"\$@\"" > enhsp
    chmod +x enhsp
fi

